name: yacht_master_admin
description: Yacht master admin panel


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  get: ^4.6.5
  sizer: ^2.0.15
  google_fonts: ^5.1.0
  intl: ^0.18.1
  image_picker_web: ^3.1.1
  syncfusion_flutter_datagrid: ^22.2.8
  desktop_window: ^0.4.0
  flutter_spinkit: ^5.2.0
  bot_toast: ^4.0.4
  transparent_image: ^2.0.1
  quill_html_editor: ^2.2.3
  flutter_widget_from_html_core: ^0.10.3
  url_launcher: ^6.1.12
  circular_profile_avatar: ^2.0.5
  cached_network_image: ^3.2.3
  flutter_dropzone: ^3.0.6
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_auth_web: ^5.6.2
  custom_pop_up_menu: ^1.2.4
  responsive_framework: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^9.4.0
  timeago: ^3.5.0
  badges: ^3.1.2
  webview_flutter: ^4.4.1
  flutter_local_notifications: ^15.1.1
  file_picker: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/